version: '3'

services: 
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
      - MYSQL_PASSWORD=test
  spring-docker-service:
    image: spring-docker-service
    build:
      context: ./ANGULAR/portMaster
      dockerfile: ./Dockerfile
    depends_on:
      - docker-mysql
    ports:
      - 7070:8080
    environment:
      - CATALINA_OPTS=-Dspring.profiles.active=container
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=test
      - DATABASE_PASSWORD=test
      - DATABASE_NAME=testdb  
      - DATABASE_PORT=3306
  angular-docker-service:
    image: angular-docker-service
    build:
      context: ./ANGULAR/portMaster
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200